# This is a basic workflow to help you get started with Actions

name: Compile the resume

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main ]  # Runs on every commit to main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: LaTeX compilation
  # You may pin to the exact commit or the version.
  # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: general_resume.tex
      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> $GITHUB_ENV
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.SHORT_SHA }}
          tag: ${{ env.SHORT_SHA }}
          artifacts: "general_resume.pdf"
          makeLatest: true
